/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver API: v0.0.0*/
/* Device Driver Client: v68.13.7*/
/* Firmware: v0.22.30*/
/* Profile Generator: v0.53.6.0*/
/* Stream Generator Assembly: v0.7.11.0*/
/* Transceiver Evaluation Software: v0.26.0*/
/* ADRV9001 Plugin: v0.26.0*/

#include "begin_receiving.h"

int begin_receiving(adi_adrv9001_Device_t * adrv9001Device_0)
{
	int32_t error_code = 0;

	error_code = adi_adrv9001_Radio_ChannelEnableMode_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, ADI_ADRV9001_SPI_MODE);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_Radio_ChannelEnableMode_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, ADI_ADRV9001_SPI_MODE);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_Rx_FrequencyCorrection_Set(adrv9001Device_0, ADI_CHANNEL_1, 0, true);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_Rx_FrequencyCorrection_Set(adrv9001Device_0, ADI_CHANNEL_2, 0, true);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_Rx_Gain_Set(adrv9001Device_0, ADI_CHANNEL_1, 190);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_bbdc_RejectionEnable_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, ADI_ADRV9001_BBDC_REJECTION_ENABLED);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_Rx_Gain_Set(adrv9001Device_0, ADI_CHANNEL_2, 190);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_bbdc_RejectionEnable_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, ADI_ADRV9001_BBDC_REJECTION_ENABLED);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_Radio_Channel_EnableRf(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, true);
	ADI_HANDLE_ERROR(error_code);

	error_code = adi_adrv9001_Radio_Channel_EnableRf(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, true);
	ADI_HANDLE_ERROR(error_code);

	adi_adrv9001_ChannelState_e channelState_13 = ADI_ADRV9001_CHANNEL_STANDBY;
	error_code = adi_adrv9001_Radio_Channel_State_Get(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &channelState_13);

	ADI_HANDLE_ERROR(error_code);

	adi_adrv9001_ChannelState_e channelState_14 = ADI_ADRV9001_CHANNEL_STANDBY;
	error_code = adi_adrv9001_Radio_Channel_State_Get(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, &channelState_14);

	ADI_HANDLE_ERROR(error_code);

	return error_code;
}